# This is a CircleCI configuration file for a Terraform workflow. The version field specifies the version 
# of the CircleCI configuration file format, which is 2.1 in this case.
version: 2.1

jobs: ## The jobs section defines three jobs, each with its own Docker image: init, format, and plan.
  init: ## The init job contains two steps.  
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:   ## The first step, checkout, retrieves the source code from the repository.
      - checkout
      - run:  ## The second step, run, initializes Terraform in the infrastructure/ directory.
          name: Initialise Terraform
          command: |
            terraform -chdir==infrastructure/ init
    
  format: ## The format job has two steps. 
    docker: 
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace: ## The first step, attach_workspace, attaches the workspace to the current working directory.
          at: .
      - run: ##  The second step, run, formats Terraform files in the infrastructure/ directory using the fmt -recursive command.
          name: Format Terraform Files
          command: |
            terraform -chdir=infrastructure/ fmt -recursive

  plan: ##The plan job has one step, run, which plans the infrastructure using the Terraform plan command in the infrastructure/ directory.
    docker:  
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - run:
          name: Plan the infrastructure 
          command: |
            terraform -chdir=infrastructure/ plan

  # apply:
  #   docker:
  #     - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
  #   steps:
  #     - run:
  #         name: terraform apply 
  #         command: |
            # terraform -chdir=infrastructure/ apply -auto-approve 
            
workflows: ##The workflows section specifies the workflow for the Terraform plan-approve-apply process.
  version: 2.1
  plan_approve_apply: ##  The plan_approve_apply workflow consists of four jobs: 
    jobs:  ## checkout, init, fmt, and plan, with dependencies specified using the requires field.
      - checkout
      - init:
          requires:
            - checkout
      - fmt:
          requires:
            - init
      - plan:
          requires:
            - fmt
      - wait-for-approval: ## The last step, wait-for-approval, is a type of approval step that waits 
          type: approval  ## for manual approval before continuing to the next step in the workflow.
          requires:
            - plan
      # - apply:
      #     requires:
      #       - wait-for-approval